/**
 * Die wichtigsten türkischen Wörter & Phrasen (~500), kuratiert nach
 * Alltagshäufigkeit und in thematischen Blöcken aufsteigender Schwierigkeit.
 * Der Wortschatz-Trainer teilt die Liste in Packs à 10 – die Reihenfolge
 * hier bestimmt die Lernreihenfolge. Format: [deutsch, türkisch].
 *
 * Jedes gelernte Wort wandert automatisch in die SM-2-Wiederholung.
 */

export interface FrequencyWord {
  rank: number;
  source: string;
  target: string;
  category: string;
}

const BLOCKS: { category: string; words: [string, string][] }[] = [
  {
    category: "Überlebens-Phrasen",
    words: [
      ["Hallo", "merhaba"],
      ["ja", "evet"],
      ["nein", "hayır"],
      ["danke", "teşekkürler"],
      ["bitte (Bitte um etwas)", "lütfen"],
      ["Entschuldigung", "affedersiniz"],
      ["OK / in Ordnung", "tamam"],
      ["Ich verstehe nicht.", "Anlamıyorum."],
      ["Ich weiß nicht.", "Bilmiyorum."],
      ["Sprechen Sie Deutsch?", "Almanca biliyor musunuz?"],
      ["Können Sie das wiederholen?", "Tekrar eder misiniz?"],
      ["langsam", "yavaş"],
      ["Hilfe!", "İmdat!"],
      ["Wo ist die Toilette?", "Tuvalet nerede?"],
      ["Wie bitte?", "Efendim?"],
      ["vielen Dank", "çok teşekkür ederim"],
      ["gern geschehen", "rica ederim"],
      ["Es tut mir leid.", "Özür dilerim."],
      ["kein Problem", "sorun değil"],
      ["natürlich", "tabii"],
    ],
  },
  {
    category: "Pronomen & Grundwörter",
    words: [
      ["ich", "ben"],
      ["du", "sen"],
      ["er/sie/es", "o"],
      ["wir", "biz"],
      ["ihr", "siz"],
      ["sie (Mehrzahl)", "onlar"],
      ["das / dies", "bu"],
      ["jenes", "şu"],
      ["hier", "burada"],
      ["dort", "orada"],
      ["was", "ne"],
      ["wer", "kim"],
      ["wo", "nerede"],
      ["wann", "ne zaman"],
      ["warum", "neden"],
      ["wie", "nasıl"],
      ["wie viel", "ne kadar"],
      ["welcher", "hangi"],
      ["etwas", "bir şey"],
      ["nichts", "hiçbir şey"],
      ["alle / alles", "hepsi"],
      ["viel / sehr", "çok"],
      ["wenig", "az"],
      ["ein bisschen", "biraz"],
      ["und", "ve"],
      ["aber", "ama"],
      ["oder", "veya"],
      ["weil / denn", "çünkü"],
      ["mit", "ile"],
      ["ohne", "-sız / -siz (ohne)"],
    ],
  },
  {
    category: "Begrüßung & Höflichkeit",
    words: [
      ["Guten Morgen", "günaydın"],
      ["Guten Tag (tagsüber)", "iyi günler"],
      ["Guten Abend", "iyi akşamlar"],
      ["Gute Nacht", "iyi geceler"],
      ["Tschüss (wenn man geht)", "hoşça kal"],
      ["Tschüss (wenn man bleibt)", "güle güle"],
      ["Bis später!", "Görüşürüz!"],
      ["Wie geht es dir?", "Nasılsın?"],
      ["Wie geht es Ihnen?", "Nasılsınız?"],
      ["Mir geht es gut.", "İyiyim."],
      ["Und dir?", "Sen nasılsın?"],
      ["Willkommen!", "Hoş geldiniz!"],
      ["Antwort auf „Willkommen“", "Hoş bulduk!"],
      ["Freut mich!", "Memnun oldum!"],
      ["ich auch", "ben de"],
      ["Herr (Anrede)", "bey"],
      ["Frau (Anrede)", "hanım"],
      ["Guten Appetit!", "Afiyet olsun!"],
      ["Gute Besserung!", "Geçmiş olsun!"],
      ["Herzlichen Glückwunsch!", "Tebrikler!"],
    ],
  },
  {
    category: "Zahlen & Mengen",
    words: [
      ["eins", "bir"],
      ["zwei", "iki"],
      ["drei", "üç"],
      ["vier", "dört"],
      ["fünf", "beş"],
      ["sechs", "altı"],
      ["sieben", "yedi"],
      ["acht", "sekiz"],
      ["neun", "dokuz"],
      ["zehn", "on"],
      ["zwanzig", "yirmi"],
      ["dreißig", "otuz"],
      ["vierzig", "kırk"],
      ["fünfzig", "elli"],
      ["hundert", "yüz"],
      ["tausend", "bin"],
      ["halb", "yarım"],
      ["Stück", "tane"],
      ["Kilo", "kilo"],
      ["erste(r)", "birinci"],
    ],
  },
  {
    category: "Zeit",
    words: [
      ["heute", "bugün"],
      ["gestern", "dün"],
      ["morgen (Tag)", "yarın"],
      ["jetzt", "şimdi"],
      ["später", "sonra"],
      ["zuerst / vorher", "önce"],
      ["die Stunde / Uhr", "saat"],
      ["Wie spät ist es?", "Saat kaç?"],
      ["Um wie viel Uhr?", "Saat kaçta?"],
      ["die Minute", "dakika"],
      ["der Tag", "gün"],
      ["die Woche", "hafta"],
      ["das Wochenende", "hafta sonu"],
      ["der Monat", "ay"],
      ["das Jahr", "yıl"],
      ["der Morgen", "sabah"],
      ["der Mittag", "öğle"],
      ["der Abend", "akşam"],
      ["die Nacht", "gece"],
      ["jeden Tag", "her gün"],
      ["manchmal", "bazen"],
      ["immer", "her zaman"],
      ["nie", "hiç"],
      ["meistens", "genelde"],
      ["früh", "erken"],
      ["spät", "geç"],
      ["Montag", "pazartesi"],
      ["Samstag", "cumartesi"],
      ["Sonntag", "pazar"],
      ["der Sommer", "yaz"],
    ],
  },
  {
    category: "Familie & Menschen",
    words: [
      ["die Familie", "aile"],
      ["die Mutter", "anne"],
      ["der Vater", "baba"],
      ["das Kind", "çocuk"],
      ["das Geschwister", "kardeş"],
      ["die große Schwester", "abla"],
      ["der große Bruder", "abi"],
      ["der Sohn", "oğul"],
      ["die Tochter", "kız"],
      ["die Frau", "kadın"],
      ["der Mann", "adam"],
      ["der Ehemann", "koca"],
      ["die Ehefrau", "eş"],
      ["der Freund / die Freundin", "arkadaş"],
      ["der Nachbar", "komşu"],
      ["der Mensch", "insan"],
      ["die Leute", "insanlar"],
      ["der Name", "ad"],
      ["mein Name", "adım"],
      ["der Gast", "misafir"],
    ],
  },
  {
    category: "Essen & Trinken 1",
    words: [
      ["das Wasser", "su"],
      ["der Tee", "çay"],
      ["der Kaffee", "kahve"],
      ["die Milch", "süt"],
      ["das Brot", "ekmek"],
      ["der Käse", "peynir"],
      ["das Ei", "yumurta"],
      ["das Fleisch", "et"],
      ["das Hähnchen", "tavuk"],
      ["der Fisch", "balık"],
      ["der Reis", "pilav"],
      ["die Suppe", "çorba"],
      ["der Salat", "salata"],
      ["das Obst", "meyve"],
      ["das Gemüse", "sebze"],
      ["der Apfel", "elma"],
      ["die Tomate", "domates"],
      ["der Zucker", "şeker"],
      ["das Salz", "tuz"],
      ["das Frühstück", "kahvaltı"],
    ],
  },
  {
    category: "Essen & Trinken 2",
    words: [
      ["das Essen / Gericht", "yemek"],
      ["das Mittagessen", "öğle yemeği"],
      ["das Abendessen", "akşam yemeği"],
      ["das Restaurant", "restoran"],
      ["die Speisekarte", "menü"],
      ["die Rechnung", "hesap"],
      ["der Kellner", "garson"],
      ["lecker", "lezzetli"],
      ["scharf", "acı"],
      ["süß", "tatlı"],
      ["der Nachtisch", "tatlı (Nachtisch)"],
      ["hungrig", "aç"],
      ["satt", "tok"],
      ["Ich bin satt.", "Doydum."],
      ["Ich möchte …", "… istiyorum"],
      ["Was möchten Sie?", "Ne istersiniz?"],
      ["Die Rechnung, bitte.", "Hesap, lütfen."],
      ["das Glas", "bardak"],
      ["der Teller", "tabak"],
      ["das Messer", "bıçak"],
    ],
  },
  {
    category: "Verben 1 – die wichtigsten",
    words: [
      ["kommen", "gelmek"],
      ["gehen", "gitmek"],
      ["machen / tun", "yapmak"],
      ["sein (existieren)", "olmak"],
      ["essen", "yemek yemek"],
      ["trinken", "içmek"],
      ["sehen", "görmek"],
      ["schauen", "bakmak"],
      ["nehmen / kaufen", "almak"],
      ["geben", "vermek"],
      ["wollen", "istemek"],
      ["wissen / können (Sprache)", "bilmek"],
      ["verstehen", "anlamak"],
      ["sprechen", "konuşmak"],
      ["sagen", "söylemek"],
      ["hören", "duymak"],
      ["zuhören", "dinlemek"],
      ["lesen", "okumak"],
      ["schreiben", "yazmak"],
      ["lernen", "öğrenmek"],
    ],
  },
  {
    category: "Verben 2 – Alltag",
    words: [
      ["aufstehen", "kalkmak"],
      ["schlafen", "uyumak"],
      ["arbeiten", "çalışmak"],
      ["wohnen / sitzen", "oturmak"],
      ["warten", "beklemek"],
      ["suchen", "aramak"],
      ["finden", "bulmak"],
      ["helfen", "yardım etmek"],
      ["lieben / mögen", "sevmek"],
      ["denken", "düşünmek"],
      ["fahren (Auto)", "sürmek"],
      ["laufen / zu Fuß gehen", "yürümek"],
      ["rennen", "koşmak"],
      ["spielen", "oynamak"],
      ["öffnen", "açmak"],
      ["schließen", "kapatmak"],
      ["beginnen", "başlamak"],
      ["enden / aufhören", "bitmek"],
      ["kochen (Essen machen)", "yemek yapmak"],
      ["sich treffen", "buluşmak"],
    ],
  },
  {
    category: "Adjektive 1",
    words: [
      ["gut", "iyi"],
      ["schlecht", "kötü"],
      ["schön", "güzel"],
      ["groß", "büyük"],
      ["klein", "küçük"],
      ["neu", "yeni"],
      ["alt (Sache)", "eski"],
      ["jung", "genç"],
      ["alt (Mensch)", "yaşlı"],
      ["lang / groß (Mensch)", "uzun"],
      ["kurz / klein (Mensch)", "kısa"],
      ["teuer", "pahalı"],
      ["günstig", "ucuz"],
      ["heiß", "sıcak"],
      ["kalt", "soğuk"],
      ["schnell", "hızlı"],
      ["einfach / leicht", "kolay"],
      ["schwierig", "zor"],
      ["voll", "dolu"],
      ["leer / frei", "boş"],
    ],
  },
  {
    category: "Adjektive 2 & Farben",
    words: [
      ["müde", "yorgun"],
      ["krank", "hasta"],
      ["gesund", "sağlıklı"],
      ["glücklich", "mutlu"],
      ["traurig", "üzgün"],
      ["wichtig", "önemli"],
      ["richtig", "doğru"],
      ["falsch", "yanlış"],
      ["sauber", "temiz"],
      ["schmutzig", "kirli"],
      ["weit / fern", "uzak"],
      ["nah", "yakın"],
      ["beschäftigt / voll (Tag)", "yoğun"],
      ["fertig / bereit", "hazır"],
      ["weiß", "beyaz"],
      ["schwarz", "siyah"],
      ["rot", "kırmızı"],
      ["blau", "mavi"],
      ["grün", "yeşil"],
      ["gelb", "sarı"],
    ],
  },
  {
    category: "Zuhause & Wohnen",
    words: [
      ["das Haus", "ev"],
      ["die Wohnung", "daire"],
      ["das Zimmer", "oda"],
      ["die Küche", "mutfak"],
      ["das Bad", "banyo"],
      ["das Wohnzimmer", "salon"],
      ["der Balkon", "balkon"],
      ["die Tür", "kapı"],
      ["das Fenster", "pencere"],
      ["der Tisch", "masa"],
      ["der Stuhl", "sandalye"],
      ["das Bett", "yatak"],
      ["der Schlüssel", "anahtar"],
      ["die Etage / der Stock", "kat"],
      ["der Garten", "bahçe"],
      ["die Straße", "sokak"],
      ["die Adresse", "adres"],
      ["die Miete", "kira"],
      ["zu Hause", "evde"],
      ["nach Hause", "eve"],
    ],
  },
  {
    category: "Stadt & Orte",
    words: [
      ["die Stadt", "şehir"],
      ["das Dorf", "köy"],
      ["der Ort / Platz", "yer"],
      ["der Markt / Supermarkt", "market"],
      ["der Wochenmarkt", "pazar (Markt)"],
      ["das Geschäft", "dükkan"],
      ["die Apotheke", "eczane"],
      ["das Krankenhaus", "hastane"],
      ["die Schule", "okul"],
      ["die Universität", "üniversite"],
      ["die Bank", "banka"],
      ["die Post", "postane"],
      ["die Polizei", "polis"],
      ["die Moschee", "cami"],
      ["der Park", "park"],
      ["das Museum", "müze"],
      ["das Kino", "sinema"],
      ["das Meer", "deniz"],
      ["der Strand", "plaj"],
      ["das Zentrum", "merkez"],
    ],
  },
  {
    category: "Verkehr & Reisen",
    words: [
      ["der Bus", "otobüs"],
      ["die Haltestelle", "durak"],
      ["der Zug", "tren"],
      ["das Flugzeug", "uçak"],
      ["der Flughafen", "havalimanı"],
      ["das Taxi", "taksi"],
      ["das Auto", "araba"],
      ["das Fahrrad", "bisiklet"],
      ["das Schiff / die Fähre", "vapur"],
      ["das Ticket", "bilet"],
      ["der Reisepass", "pasaport"],
      ["der Koffer", "bavul"],
      ["die Tasche", "çanta"],
      ["die Reise", "yolculuk"],
      ["der Urlaub", "tatil"],
      ["das Hotel", "otel"],
      ["die Reservierung", "rezervasyon"],
      ["rechts", "sağda"],
      ["links", "solda"],
      ["geradeaus", "düz"],
    ],
  },
  {
    category: "Einkaufen & Geld",
    words: [
      ["das Geld", "para"],
      ["die Lira", "lira"],
      ["der Preis", "fiyat"],
      ["Wie viel kostet das?", "Bu ne kadar?"],
      ["kaufen", "satın almak"],
      ["verkaufen", "satmak"],
      ["bezahlen", "ödemek"],
      ["die Kreditkarte", "kredi kartı"],
      ["bar", "nakit"],
      ["das Wechselgeld", "para üstü"],
      ["billig(er) machen / Rabatt", "indirim"],
      ["der Kunde", "müşteri"],
      ["offen / geöffnet", "açık"],
      ["geschlossen", "kapalı"],
      ["Bitte sehr! / Ja, bitte?", "Buyurun!"],
      ["Haben Sie …?", "… var mı?"],
      ["es gibt", "var"],
      ["es gibt nicht", "yok"],
      ["frisch", "taze"],
      ["die Kleidung", "kıyafet"],
    ],
  },
  {
    category: "Körper & Gesundheit",
    words: [
      ["der Kopf", "baş"],
      ["das Auge", "göz"],
      ["das Ohr", "kulak"],
      ["der Mund", "ağız"],
      ["die Hand", "el"],
      ["der Arm", "kol"],
      ["das Bein", "bacak"],
      ["der Fuß", "ayak"],
      ["der Bauch", "karın"],
      ["der Rücken", "sırt"],
      ["das Herz", "kalp"],
      ["der Zahn", "diş"],
      ["der Hals", "boğaz"],
      ["der Schmerz", "ağrı"],
      ["… tut weh", "… ağrıyor"],
      ["das Fieber", "ateş"],
      ["der Arzt", "doktor"],
      ["das Medikament", "ilaç"],
      ["die Erkältung / Grippe", "grip"],
      ["Was fehlt Ihnen?", "Neyiniz var?"],
    ],
  },
  {
    category: "Arbeit & Schule",
    words: [
      ["die Arbeit / der Job", "iş"],
      ["das Büro", "ofis"],
      ["der Kollege", "iş arkadaşı"],
      ["der Chef", "patron"],
      ["das Meeting", "toplantı"],
      ["der Lehrer", "öğretmen"],
      ["der Schüler / Student", "öğrenci"],
      ["der Unterricht / die Lektion", "ders"],
      ["der Kurs", "kurs"],
      ["das Wort", "kelime"],
      ["der Satz", "cümle"],
      ["die Frage", "soru"],
      ["die Antwort", "cevap"],
      ["das Beispiel", "örnek"],
      ["die Sprache", "dil"],
      ["Türkisch", "Türkçe"],
      ["Deutsch", "Almanca"],
      ["Englisch", "İngilizce"],
      ["der Beruf", "meslek"],
      ["der Ingenieur", "mühendis"],
    ],
  },
  {
    category: "Natur & Wetter",
    words: [
      ["das Wetter", "hava"],
      ["die Sonne", "güneş"],
      ["der Regen", "yağmur"],
      ["der Schnee", "kar"],
      ["der Wind", "rüzgar"],
      ["die Wolke", "bulut"],
      ["der Himmel", "gökyüzü"],
      ["der Baum", "ağaç"],
      ["die Blume", "çiçek"],
      ["der Berg", "dağ"],
      ["der Fluss", "nehir"],
      ["der See", "göl"],
      ["die Insel", "ada"],
      ["das Tier", "hayvan"],
      ["der Hund", "köpek"],
      ["die Katze", "kedi"],
      ["der Vogel", "kuş"],
      ["Das Wetter ist schön.", "Hava güzel."],
      ["Es regnet.", "Yağmur yağıyor."],
      ["der Frühling", "ilkbahar"],
    ],
  },
  {
    category: "Kommunikation & Technik",
    words: [
      ["das Telefon / Handy", "telefon"],
      ["die Nummer", "numara"],
      ["anrufen", "aramak (telefonla)"],
      ["die Nachricht", "mesaj"],
      ["die E-Mail", "e-posta"],
      ["das Internet", "internet"],
      ["das WLAN", "wifi"],
      ["das Passwort", "şifre"],
      ["der Computer", "bilgisayar"],
      ["das Foto", "fotoğraf"],
      ["die Musik", "müzik"],
      ["der Film", "film"],
      ["die Nachrichten (News)", "haberler"],
      ["das Buch", "kitap"],
      ["die Zeitung", "gazete"],
      ["kaputt", "bozuk"],
      ["es funktioniert nicht", "çalışmıyor"],
      ["das Ladegerät", "şarj aleti"],
      ["Hallo? (am Telefon)", "Alo?"],
      ["besetzt / beschäftigt", "meşgul"],
    ],
  },
  {
    category: "Gefühle & Meinung",
    words: [
      ["die Liebe", "aşk"],
      ["das Glück", "mutluluk"],
      ["die Angst", "korku"],
      ["aufgeregt", "heyecanlı"],
      ["besorgt", "endişeli"],
      ["wütend", "kızgın"],
      ["überrascht", "şaşkın"],
      ["gelangweilt", "sıkılmış"],
      ["meiner Meinung nach", "bence"],
      ["deiner Meinung nach", "sence"],
      ["Ich stimme zu.", "Katılıyorum."],
      ["Ich stimme nicht zu.", "Katılmıyorum."],
      ["Du hast recht.", "Haklısın."],
      ["vielleicht", "belki"],
      ["bestimmt / sicher", "kesinlikle"],
      ["interessant", "ilginç"],
      ["langweilig", "sıkıcı"],
      ["lustig", "komik"],
      ["Mach dir keine Sorgen.", "Merak etme."],
      ["Ich vermisse dich.", "Seni özledim."],
    ],
  },
  {
    category: "Nützliche Sätze 1",
    words: [
      ["Wie heißt du?", "Adın ne?"],
      ["Ich heiße …", "Benim adım …"],
      ["Woher kommst du?", "Nerelisin?"],
      ["Ich komme aus Deutschland.", "Almanyalıyım."],
      ["Wo wohnst du?", "Nerede oturuyorsun?"],
      ["Ich wohne in Berlin.", "Berlin'de oturuyorum."],
      ["Wie alt bist du?", "Kaç yaşındasın?"],
      ["Ich bin 30 Jahre alt.", "Otuz yaşındayım."],
      ["Ich lerne Türkisch.", "Türkçe öğreniyorum."],
      ["Ich spreche ein bisschen Türkisch.", "Biraz Türkçe konuşuyorum."],
      ["Was bedeutet das?", "Bu ne demek?"],
      ["Wie sagt man … auf Türkisch?", "Türkçede … nasıl denir?"],
      ["Kannst du mir helfen?", "Bana yardım eder misin?"],
      ["Einen Moment, bitte.", "Bir dakika, lütfen."],
      ["Ich habe eine Frage.", "Bir sorum var."],
      ["Kein Stress / mach langsam", "Kolay gelsin!"],
      ["Was machst du?", "Ne yapıyorsun?"],
      ["Wohin gehst du?", "Nereye gidiyorsun?"],
      ["Ich muss gehen.", "Gitmem lazım."],
      ["Bis morgen!", "Yarın görüşürüz!"],
    ],
  },
  {
    category: "Nützliche Sätze 2",
    words: [
      ["Was hast du gestern gemacht?", "Dün ne yaptın?"],
      ["Was machst du am Wochenende?", "Hafta sonu ne yapıyorsun?"],
      ["Wollen wir uns treffen?", "Buluşalım mı?"],
      ["Passt es dir morgen?", "Yarın uygun musun?"],
      ["Ich habe keine Zeit.", "Vaktim yok."],
      ["Ich bin unterwegs.", "Yoldayım."],
      ["Ich komme gleich.", "Hemen geliyorum."],
      ["Wo bist du?", "Neredesin?"],
      ["Was ist los?", "Ne oldu?"],
      ["Alles in Ordnung?", "Her şey yolunda mı?"],
      ["Ich bin müde.", "Yorgunum."],
      ["Ich habe Hunger.", "Acıktım."],
      ["Ich habe Durst.", "Susadım."],
      ["Das gefällt mir.", "Bunu beğendim."],
      ["Ich liebe dich.", "Seni seviyorum."],
      ["Viel Glück!", "İyi şanslar!"],
      ["Gute Reise!", "İyi yolculuklar!"],
      ["Schönes Wochenende!", "İyi hafta sonları!"],
      ["Willst du mitkommen?", "Gelmek ister misin?"],
      ["Sehr gerne!", "Çok isterim!"],
    ],
  },
  {
    category: "Kleidung & Alltagsdinge",
    words: [
      ["das Hemd", "gömlek"],
      ["das T-Shirt", "tişört"],
      ["die Hose", "pantolon"],
      ["das Kleid", "elbise"],
      ["der Schuh", "ayakkabı"],
      ["die Jacke", "ceket"],
      ["der Mantel", "mont"],
      ["der Pullover", "kazak"],
      ["die Socke", "çorap"],
      ["der Hut / die Mütze", "şapka"],
      ["die Brille", "gözlük"],
      ["die Uhr (Armbanduhr)", "kol saati"],
      ["die Größe (Kleidung)", "beden"],
      ["anprobieren", "denemek"],
      ["tragen (Kleidung)", "giymek"],
      ["die Farbe", "renk"],
      ["die Seife", "sabun"],
      ["das Handtuch", "havlu"],
      ["die Zahnbürste", "diş fırçası"],
      ["das Geschenk", "hediye"],
    ],
  },
  {
    category: "Feste & Kultur",
    words: [
      ["das Fest / der Feiertag", "bayram"],
      ["der Geburtstag", "doğum günü"],
      ["Alles Gute zum Geburtstag!", "Doğum günün kutlu olsun!"],
      ["die Party", "parti"],
      ["die Einladung", "davet"],
      ["die Hochzeit", "düğün"],
      ["feiern", "kutlamak"],
      ["tanzen", "dans etmek"],
      ["singen", "şarkı söylemek"],
      ["das Lied", "şarkı"],
      ["Kompliment an den Koch", "Eline sağlık!"],
      ["Frohes Fest!", "İyi bayramlar!"],
      ["die Gesundheit", "sağlık"],
      ["Auf Ihre Gesundheit! (Prost)", "Şerefe!"],
      ["der Spaß", "eğlence"],
      ["sich amüsieren", "eğlenmek"],
      ["das Glück (Schicksal)", "şans"],
      ["die Überraschung", "sürpriz"],
      ["der Sport", "spor"],
      ["der Fußball", "futbol"],
    ],
  },
  // TODO für B1 und B2:
  // Um die CEFR-Ziele zu erreichen, können hier weitere Themenblöcke hinzugefügt werden.
  // B1-Ziel: ca. 2.000 bis 2.500 Wörter (z.B. Medien, Politik, Umwelt, detaillierte Beschreibungen)
  // B2-Ziel: ca. 4.000 bis 5.000 Wörter (z.B. Fachdiskussionen, abstraktes Vokabular, Redewendungen)
  // Jedes neue Wort wird automatisch durch das frequencyRank-Mapping in den Trainer aufgenommen.
];

export const FREQUENCY_VOCAB: FrequencyWord[] = BLOCKS.flatMap((block, blockIndex) =>
  block.words.map(([source, target], i) => ({
    rank: BLOCKS.slice(0, blockIndex).reduce((sum, b) => sum + b.words.length, 0) + i + 1,
    source,
    target,
    category: block.category,
  }))
);

export const PACK_SIZE = 10;

export function packCount(): number {
  return Math.ceil(FREQUENCY_VOCAB.length / PACK_SIZE);
}

export function packWords(packIndex: number): FrequencyWord[] {
  return FREQUENCY_VOCAB.slice(packIndex * PACK_SIZE, (packIndex + 1) * PACK_SIZE);
}
